default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: pass123
  host: localhost
  port: 5432

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: transport_app_development

test:
  <<: *default
  database: transport_app_test
# production:
#   primary: &primary_production
#     <<: *default
#     database: transport_app_production
#     username: transport_app
#     password: <%= ENV["TRANSPORT_APP_DATABASE_PASSWORD"] %>
#   cache:
#     <<: *primary_production
#     database: transport_app_production_cache
#     migrations_paths: db/cache_migrate
#   queue:
#     <<: *primary_production
#     database: transport_app_production_queue
#     migrations_paths: db/queue_migrate
#   cable:
#     <<: *primary_production
#     database: transport_app_production_cable
#     migrations_paths: db/cable_migrate
